# 创建numpy数组

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
b = np.arange(10)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
range(10)

range(0, 10)

In [7]:
b = b.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 选取元素

In [8]:
b[1,4]

9

In [9]:
b[1][4]

9

In [10]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 数据类型

In [11]:
type(a)

numpy.ndarray

In [12]:
a.dtype

dtype('int32')

# 索引和切片

In [13]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
b[:1,:2]

array([[0, 1]])

In [15]:
b[:,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [16]:
b[:,::-1]

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [17]:
b[::-1,::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

# 数组组合
## 水平组合
## 垂直组合
## 深度组合
## 列组合

In [18]:
a

array([[1, 2],
       [3, 4]])

In [19]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
np.hstack((a,b))

array([[1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 6, 7, 8, 9]])

In [21]:
c = np.array([[5,6],[7,8]])

In [22]:
c

array([[5, 6],
       [7, 8]])

In [23]:
a

array([[1, 2],
       [3, 4]])

In [25]:
np.vstack((a,c))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
np.concatenate((a,c),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
np.concatenate((a,c),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [29]:
a

array([[1, 2],
       [3, 4]])

In [30]:
c

array([[5, 6],
       [7, 8]])

In [32]:
np.dstack((a,c))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

# 数组分割

In [33]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
d = np.arange(16).reshape(4 ,4)

In [35]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.hsplit(d,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [37]:
np.hsplit(d,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]), array([[ 1],
        [ 5],
        [ 9],
        [13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [41]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.vsplit(d,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [42]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.split(d,2,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [40]:
np.split(d,4,axis=0)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [43]:
e = np.arange(27).reshape(3,3,3)

In [44]:
e

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [45]:
np.dsplit(e,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

# 读写文件

In [ ]:
b

In [ ]:
np.savetxt('D:/arrayb.txt',b)

In [ ]:
arr = np.loadtxt('000001.txt',delimiter=',',usecols=[4,5])

In [ ]:
arr

In [ ]:
max(arr[0])

In [ ]:
np.max(arr[0])

In [ ]:
np.mean(arr[0])

In [ ]:
np.average(arr[0],weights=arr[1])

In [ ]:
arr[0]

In [ ]:
len(arr[:,0])

In [ ]:
e = (arr[:-1,0] - arr[1:,0])/arr[1:,0]*100

In [ ]:
arr[:,0]

In [ ]:
np.diff(arr[:,0])

In [ ]:
np.median(arr[:,0])

In [ ]:
np.var(arr[:,0])

In [ ]:
np.std(arr[:,0])

In [ ]:
e

In [ ]:
e[np.where(e>0)]

In [ ]:
(c,v) = np.loadtxt('000001.txt',delimiter=',',usecols = [5,6],unpack=True)

In [ ]:
c

In [ ]:
v

In [ ]:
b

In [ ]:
b / 2

In [ ]:
c = b*2

In [ ]:
b

In [ ]:
c

In [ ]:
b * c

In [ ]:
np.dot(b,c.T)

In [ ]:
c.T

In [ ]:
np.exp(b,2)

# 基本处理函数

![numpy练习](https://cloud.tencent.com/developer/article/1047877)

1. 导入numpy库并取别名为np (★☆☆)
2. 打印输出numpy的版本和配置信息 (★☆☆)
3. 创建长度为10的零向量 (★☆☆)
4. 获取数组所占内存大小 (★☆☆)
5. 怎么用命令行获取numpy add函数的文档说明？ (★☆☆)
6. 创建一个长度为10的零向量，并把第五个值赋值为1 (★☆☆)
7. 创建一个值域为10到49的向量 (★☆☆)
8. 将一个向量进行反转（第一个元素变为最后一个元素） (★☆☆)
9. 创建一个3×3的矩阵，值域为0到8(★☆☆)
10. 从数组[1, 2, 0, 0, 4, 0]中找出非0元素的位置索引 (★☆☆)
11. 创建一个3×3的单位矩阵 (★☆☆)
12. 创建一个3x3x3的随机数组(★☆☆)
13. 创建一个10×10的随机数组，并找出该数组中的最大值与最小值(★☆☆)
14. 创建一个长度为30的随机向量，并求它的平均值 (★☆☆)
15. 创建一个2维数组，该数组边界值为1，内部的值为0 (★☆☆)
16. 如何用0来填充一个数组的边界？ (★☆☆)
17. 下面表达式运行的结果是什么？(★☆☆)
18. 创建一个5×5的矩阵，且设置值1, 2, 3, 4在其对角线下面一行(★☆☆)
19. 创建一个8×8的棋盘矩阵（填充为棋盘样式） (★☆☆)
20. 思考一下形状为(6, 7, 8)的数组的形状，且第100个元素的索引(x, y, z)分别是什么？(★☆☆)

In [ ]:
class cat():
    name = 'tom'
    age = 3
    def sleep(self):
        print('Tom 睡觉')
    def eat(self):
        print('Tom吃饭')

In [ ]:
newcat = cat()

In [ ]:
newcat.sleep()

In [ ]:
class cat():
    def action(self):
        print('打豆豆')

In [ ]:
newcat = cat()

In [ ]:
newcat.action()

In [ ]:
newcat.sleep()

In [ ]:
class cat():
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def sleep(self):
        print('睡觉')
    def eat(self):
        print('吃饭')

In [ ]:
newcat = cat('tom',3)

In [ ]:
newcat.name