In [1]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
plt.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
plt.rcParams['axes.unicode_minus']=False #用来正常显示负号

In [3]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [4]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = b.reshape(2,5)

# 选取元素

In [8]:
b[1,4]

9

数据类型

In [9]:
b.dtype

dtype('int32')

索引和切片

In [10]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
b[:1,:2]

array([[0, 1]])

数组合并

In [13]:
a

array([[1, 2],
       [3, 4]])

In [12]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
np.hstack((a,b))

array([[1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 6, 7, 8, 9]])

In [16]:
c = np.array([[5,6],[7,8]])

In [17]:
np.vstack((a,c))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

1为水平组合，0为垂直组合

In [21]:
np.concatenate((a,c),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

深度组合

In [25]:
np.dstack((a,c))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

分割

In [26]:
d = np.arange(16).reshape(4,4)

In [27]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

数字代表分为几部分

In [28]:
np.hsplit(d,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [30]:
np.vsplit(d,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

0为垂直，1为水平

In [32]:
np.split(d,2,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

深度分割只支持3维以上数组

In [35]:
e = np.arange(27).reshape(3,3,3)
e

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

读写文件

In [36]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

写文件
np.savetxt('文件名',b)

读文件

In [ ]:
b = np.loadtxt("文件名",delimiter=",")