In [1]:
import numpy as np

numpy版本信息

In [2]:
print (np.__version__)
np.show_config()

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'F:/anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'F:/anaconda\\Library\\include']
blas

长度为10的0向量

In [4]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

当前数组所占内存大小

In [6]:
print(a.size*a.itemsize)

80


用命令行获取numpy add函数的文档说明

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

创建一个长度为10的零向量，并把第五个值赋值为1 

In [17]:
b = np.zeros(10)
b[4] = 1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


创建一个值域为10到49的向量 

In [19]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

将一个向量进行反转（第一个元素变为最后一个元素）

In [21]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

创建一个3×3的矩阵，值域为0到8

In [24]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

从数组[1, 2, 0, 0, 4, 0]中找出非0元素的位置索引

In [28]:
a = np.nonzero([1, 2, 0, 0, 4, 0])
print(a)

(array([0, 1, 4], dtype=int64),)


创建一个3×3的单位矩阵

In [31]:
Z = np.eye(3)
print (Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


创建一个3x3x3的随机数组

In [32]:
Z = np.random.random((3, 3, 3))
print (Z)

[[[0.09955748 0.2320595  0.30841614]
  [0.29182369 0.93740039 0.39812748]
  [0.06914062 0.72280316 0.0684372 ]]

 [[0.35103704 0.00971735 0.35022179]
  [0.92947184 0.29146877 0.56657966]
  [0.02341758 0.90023259 0.09306691]]

 [[0.97006545 0.47907333 0.1735597 ]
  [0.66191681 0.83345371 0.61297908]
  [0.80635281 0.63637996 0.10293689]]]
